"use client";

import { useEffect, useRef, useState } from "react";
import { ChevronDown, ImagePlus, Loader2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { AppSelect } from "@/components/ui/app-select";
import { Badge } from "@/components/ui/badge";
import { StringListEditor } from "@/components/system-design-admin/StringListEditor";
import { BlogEditor } from "@/components/blog-admin/BlogEditor";
import { SeoPanel } from "@/components/blog-admin/SeoPanel";
import {
  BlogFormField,
  blogControlClass,
} from "@/components/blog-admin/BlogFormField";
import { slugifyTitle, isAutoGeneratedDraftSlug, generateDraftSlug, type BlogFormValues } from "@/components/blog-admin/form-utils";
import { getApiErrorMessage } from "@/lib/api-error-message";
import { adminBlogApi } from "@/lib/api";
import { toast } from "sonner";
import { cn } from "@/lib/utils";

function Section({
  title,
  description,
  children,
  defaultOpen = true,
}: Readonly<{
  title: string;
  description?: string;
  children: React.ReactNode;
  defaultOpen?: boolean;
}>) {
  const [open, setOpen] = useState(defaultOpen);
  return (
    <section className="overflow-hidden rounded-xl border border-border bg-card shadow-sm">
      <button
        type="button"
        className="flex w-full items-start justify-between gap-3 px-4 py-3.5 text-left sm:px-5 sm:py-4"
        onClick={() => setOpen((o) => !o)}
        aria-expanded={open}
      >
        <span className="min-w-0">
          <span className="block text-sm font-semibold text-foreground sm:text-base">
            {title}
          </span>
          {description ? (
            <span className="mt-0.5 block text-xs text-muted-foreground sm:text-sm">
              {description}
            </span>
          ) : null}
        </span>
        <ChevronDown
          className={cn(
            "mt-0.5 h-5 w-5 shrink-0 text-muted-foreground transition-transform",
            open && "rotate-180",
          )}
        />
      </button>
      {open ? (
        <div className="space-y-5 border-t border-border/80 px-4 py-4 sm:space-y-6 sm:px-5 sm:py-5">
          {children}
        </div>
      ) : null}
    </section>
  );
}

interface BlogFormProps {
  readonly mode: "create" | "edit";
  readonly value: BlogFormValues;
  readonly onChange: (patch: Partial<BlogFormValues>) => void;
  readonly categories: string[];
}

async function uploadThumbnail(file: File): Promise<string> {
  const { publicUrl } = await adminBlogApi.uploadImage(file);
  return publicUrl;
}

export function BlogForm({ mode, value, onChange, categories }: BlogFormProps) {
  const thumbInputRef = useRef<HTMLInputElement>(null);
  const [uploadingThumb, setUploadingThumb] = useState(false);
  const [slugEdited, setSlugEdited] = useState(false);

  useEffect(() => {
    if (!slugEdited && mode === "edit" && !isAutoGeneratedDraftSlug(value.slug)) {
      setSlugEdited(true);
    }
  }, [mode, slugEdited, value.slug]);

  const handleTitleChange = (title: string) => {
    const patch: Partial<BlogFormValues> = { title };
    const slugIsAuto = !value.slug.trim() || isAutoGeneratedDraftSlug(value.slug);
    if (!slugEdited && slugIsAuto) {
      patch.slug = title.trim() ? slugifyTitle(title) : value.slug || generateDraftSlug();
      if (!value.seoTitle.trim() && title.trim()) patch.seoTitle = title;
    }
    onChange(patch);
  };

  const handleThumbUpload = async (file: File) => {
    setUploadingThumb(true);
    try {
      const url = await uploadThumbnail(file);
      onChange({ thumbnailUrl: url });
      toast.success("Thumbnail uploaded");
    } catch (err) {
      toast.error(getApiErrorMessage(err, "Thumbnail upload failed"));
    } finally {
      setUploadingThumb(false);
    }
  };

  return (
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_min(100%,380px)] xl:items-start xl:gap-8">
      <div className="min-w-0 space-y-4 sm:space-y-5">
        <Section
          title="Post details"
          description="Title, URL, excerpt, and publishing status."
        >
          <BlogFormField label="Title" htmlFor="blog-title">
            <Input
              id="blog-title"
              className={blogControlClass}
              value={value.title}
              onChange={(e) => handleTitleChange(e.target.value)}
              placeholder="Blog post title"
            />
          </BlogFormField>

          <BlogFormField
            label="URL slug"
            htmlFor="blog-slug"
            hint="Lowercase letters, numbers, and hyphens only."
          >
            <Input
              id="blog-slug"
              className={cn(blogControlClass, "font-mono")}
              value={value.slug}
              onChange={(e) => {
                setSlugEdited(true);
                onChange({
                  slug: e.target.value.toLowerCase().replace(/\s+/g, "-"),
                });
              }}
              placeholder="url-friendly-slug"
            />
          </BlogFormField>

          <BlogFormField
            label="Excerpt"
            htmlFor="blog-excerpt"
            hint="Shown on blog cards and search snippets."
          >
            <Textarea
              id="blog-excerpt"
              className="min-h-[88px] w-full resize-y text-base sm:text-sm"
              value={value.excerpt}
              onChange={(e) => onChange({ excerpt: e.target.value })}
              placeholder="Short summary for cards and SEO"
              maxLength={500}
            />
            <p className="mt-1.5 text-right text-xs text-muted-foreground">
              {value.excerpt.length}/500
            </p>
          </BlogFormField>

          <StringListEditor
            label="Categories"
            value={value.categories}
            onChange={(next) => onChange({ categories: next })}
            placeholder="Add category"
          />

          <BlogFormField label="Status" htmlFor="blog-status">
            <div className="flex flex-wrap items-center gap-3">
              <AppSelect
                id="blog-status"
                className={blogControlClass}
                value={value.status}
                onChange={(v) =>
                  onChange({ status: v as BlogFormValues["status"] })
                }
                options={[
                  { value: "draft", label: "Draft" },
                  { value: "published", label: "Published" },
                  { value: "archived", label: "Archived" },
                ]}
              />
              {!value.isActive ? (
                <Badge variant="outline" className="text-rose-600">
                  Deleted
                </Badge>
              ) : null}
            </div>
          </BlogFormField>
        </Section>

        <Section
          title="Featured thumbnail"
          description="Used on blog cards and social sharing previews."
        >
          <div className="grid gap-4 lg:grid-cols-[minmax(0,280px)_minmax(0,1fr)] lg:items-start lg:gap-6">
            <div className="relative aspect-video w-full overflow-hidden rounded-lg border border-border bg-muted/20">
              {value.thumbnailUrl ? (
                <>
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={value.thumbnailUrl}
                    alt="Thumbnail preview"
                    className="h-full w-full object-cover"
                  />
                  <Button
                    type="button"
                    variant="secondary"
                    size="icon"
                    className="absolute right-2 top-2 h-8 w-8 shadow-sm"
                    onClick={() => onChange({ thumbnailUrl: "" })}
                    aria-label="Remove thumbnail"
                  >
                    <X className="h-4 w-4" />
                  </Button>
                </>
              ) : (
                <div className="flex h-full min-h-[140px] items-center justify-center px-4 text-center text-sm text-muted-foreground">
                  No thumbnail yet
                </div>
              )}
            </div>

            <div className="flex min-w-0 flex-col gap-3">
              <Button
                type="button"
                variant="outline"
                className="h-11 w-full sm:w-fit"
                disabled={uploadingThumb}
                onClick={() => thumbInputRef.current?.click()}
              >
                {uploadingThumb ? (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                ) : (
                  <ImagePlus className="mr-2 h-4 w-4" />
                )}
                Upload image
              </Button>
              <Input
                className={blogControlClass}
                value={value.thumbnailUrl}
                onChange={(e) => onChange({ thumbnailUrl: e.target.value })}
                placeholder="Or paste image URL"
              />
            </div>
          </div>
          <input
            ref={thumbInputRef}
            type="file"
            accept="image/jpeg,image/png,image/webp,image/gif"
            className="hidden"
            onChange={(e) => {
              const file = e.target.files?.[0];
              e.target.value = "";
              if (file) void handleThumbUpload(file);
            }}
          />
        </Section>

        <Section title="Content" description="Main article body with rich formatting.">
          <BlogEditor
            value={value.content}
            onChange={(content) => onChange({ content })}
          />
        </Section>
      </div>

      <aside className="min-w-0 xl:sticky xl:top-20 xl:self-start">
        <div className="overflow-hidden rounded-xl border border-border bg-card shadow-sm">
          <div className="border-b border-border/80 bg-muted/20 px-4 py-3.5 sm:px-5">
            <h2 className="text-sm font-semibold text-foreground sm:text-base">
              SEO & discoverability
            </h2>
            <p className="mt-0.5 text-xs text-muted-foreground sm:text-sm">
              Optimize how this post appears in Google and social previews.
            </p>
          </div>
          <div className="p-4 sm:p-5">
            <SeoPanel form={value} onChange={onChange} />
          </div>
        </div>
      </aside>
    </div>
  );
}

interface BlogFormFooterProps {
  readonly saving: boolean;
  readonly publishing?: boolean;
  readonly autoSaveLabel?: string;
  readonly onSave: () => void;
  readonly onPublish?: () => void;
  readonly onCancel: () => void;
  readonly onDelete?: () => void;
  readonly onPreview?: () => void;
}

export function BlogFormFooter({
  saving,
  publishing,
  autoSaveLabel,
  onSave,
  onPublish,
  onCancel,
  onDelete,
  onPreview,
}: BlogFormFooterProps) {
  return (
    <div className="flex flex-col gap-4 border-t border-border/80 pt-5 sm:gap-3">
      {autoSaveLabel ? (
        <p className="text-xs text-muted-foreground">{autoSaveLabel}</p>
      ) : null}
      <div className="flex flex-col gap-2 sm:flex-row sm:flex-wrap">
        {onDelete ? (
          <Button
            type="button"
            variant="destructive"
            className="h-11 w-full sm:w-auto"
            onClick={onDelete}
          >
            Delete
          </Button>
        ) : null}
        {onPreview ? (
          <Button
            type="button"
            variant="outline"
            className="h-11 w-full sm:w-auto"
            onClick={onPreview}
          >
            Preview
          </Button>
        ) : null}
      </div>

      <div className="grid grid-cols-1 gap-2 sm:grid-cols-3 sm:justify-end">
        <Button
          type="button"
          variant="outline"
          className="h-11 w-full sm:order-1"
          onClick={onCancel}
        >
          Cancel
        </Button>
        {onPublish ? (
          <Button
            type="button"
            variant="secondary"
            className="h-11 w-full sm:order-2"
            disabled={publishing || saving}
            onClick={onPublish}
          >
            {publishing ? (
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            ) : null}
            Publish
          </Button>
        ) : null}
        <Button
          type="button"
          className="h-11 w-full sm:order-3"
          disabled={saving}
          onClick={onSave}
        >
          {saving ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}
          Save changes
        </Button>
      </div>
    </div>
  );
}
