import type {
  AdminBlogDetail,
  AdminBlogUpsertBody,
  BlogStatus,
} from "@/lib/api";

export type BlogFormValues = {
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  thumbnailUrl: string;
  categories: string[];
  status: BlogStatus;
  seoTitle: string;
  metaDescription: string;
  focusKeyword: string;
  keywords: string[];
  canonicalUrl: string;
  isActive: boolean;
};

export function slugifyTitle(title: string): string {
  return title
    .toLowerCase()
    .trim()
    .replace(/[^\w\s-]/g, "")
    .replace(/[\s_]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 120);
}

const AUTO_DRAFT_SLUG_RE = /^draft-[a-z0-9]{8,14}$/;

export function generateDraftSlug(): string {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return `draft-${crypto.randomUUID().replace(/-/g, "").slice(0, 10).toLowerCase()}`;
  }
  return `draft-${Math.random().toString(36).slice(2, 12)}`;
}

export function isAutoGeneratedDraftSlug(slug: string): boolean {
  return AUTO_DRAFT_SLUG_RE.test(slug.trim().toLowerCase());
}

export function resolveBlogSlug(form: BlogFormValues): string {
  const manualSlug = form.slug.trim().toLowerCase();
  const titleSlug = slugifyTitle(form.title);
  if (manualSlug && !isAutoGeneratedDraftSlug(manualSlug)) {
    return manualSlug;
  }
  if (titleSlug) return titleSlug;
  if (manualSlug) return manualSlug;
  return generateDraftSlug();
}

/** Keep a stable auto slug in form state before the first save. */
export function ensureFormDraftSlug(form: BlogFormValues): BlogFormValues {
  const manualSlug = form.slug.trim().toLowerCase();
  if (manualSlug) return form;
  if (slugifyTitle(form.title)) return form;
  return { ...form, slug: generateDraftSlug() };
}

export function blogFormHasDraftContent(form: BlogFormValues): boolean {
  return Boolean(
    form.title.trim() ||
      form.content.trim() ||
      form.excerpt.trim() ||
      form.thumbnailUrl.trim(),
  );
}

const NEW_BLOG_DRAFT_STORAGE_KEY = "interview-trix-new-blog-draft";

export function saveNewBlogDraftLocal(form: BlogFormValues): void {
  if (typeof window === "undefined") return;
  try {
    sessionStorage.setItem(NEW_BLOG_DRAFT_STORAGE_KEY, JSON.stringify(form));
  } catch {
    /* ignore quota errors */
  }
}

export function loadNewBlogDraftLocal(): BlogFormValues | null {
  if (typeof window === "undefined") return null;
  try {
    const raw = sessionStorage.getItem(NEW_BLOG_DRAFT_STORAGE_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw) as Partial<BlogFormValues>;
    return { ...emptyBlogForm(), ...parsed, status: "draft" };
  } catch {
    return null;
  }
}

export function clearNewBlogDraftLocal(): void {
  if (typeof window === "undefined") return;
  sessionStorage.removeItem(NEW_BLOG_DRAFT_STORAGE_KEY);
}

export function emptyBlogForm(): BlogFormValues {
  return {
    slug: "",
    title: "",
    excerpt: "",
    content: "",
    thumbnailUrl: "",
    categories: [],
    status: "draft",
    seoTitle: "",
    metaDescription: "",
    focusKeyword: "",
    keywords: [],
    canonicalUrl: "",
    isActive: true,
  };
}

export function detailToFormValues(detail: AdminBlogDetail): BlogFormValues {
  return {
    slug: detail.slug,
    title: detail.title,
    excerpt: detail.excerpt,
    content: detail.content,
    thumbnailUrl: detail.thumbnailUrl,
    categories: detail.categories ?? [],
    status: detail.status,
    seoTitle: detail.seoTitle,
    metaDescription: detail.metaDescription,
    focusKeyword: detail.focusKeyword,
    keywords: detail.keywords ?? [],
    canonicalUrl: detail.canonicalUrl ?? "",
    isActive: detail.isActive,
  };
}

export function formToUpsertBody(form: BlogFormValues): AdminBlogUpsertBody {
  const title = form.title.trim();
  const slug = resolveBlogSlug(form);
  return {
    slug,
    title,
    excerpt: form.excerpt.trim(),
    content: form.content,
    thumbnailUrl: form.thumbnailUrl.trim(),
    categories: form.categories,
    status: form.status,
    seoTitle: form.seoTitle.trim() || title,
    metaDescription: form.metaDescription.trim(),
    focusKeyword: form.focusKeyword.trim(),
    keywords: form.keywords,
    canonicalUrl: form.canonicalUrl.trim(),
  };
}

/** Autosave always persists as draft until the user explicitly publishes. */
export function formToAutoSaveBody(form: BlogFormValues): AdminBlogUpsertBody {
  return {
    ...formToUpsertBody(form),
    status: form.status === "published" ? "published" : "draft",
  };
}

export function serializeBlogFormForSave(form: BlogFormValues): string {
  return JSON.stringify(formToAutoSaveBody(form));
}

export function validateBlogForm(form: BlogFormValues): string | null {
  const slug = resolveBlogSlug(form);
  if (slug && !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) {
    return "Slug must be lowercase letters, numbers, and hyphens only";
  }
  if (form.status === "published") {
    if (!form.title.trim()) return "Title is required to publish";
    if (!form.excerpt.trim()) return "Excerpt is required to publish";
    if (!form.content.trim()) return "Content is required to publish";
    if (!form.thumbnailUrl.trim()) return "Thumbnail is required to publish";
    if (!form.seoTitle.trim()) return "SEO title is required to publish";
    if (!form.metaDescription.trim()) return "Meta description is required to publish";
  }
  return null;
}
