/** Keep in sync with interview-core/src/constants/careerCatalog.ts */
import type { IndustryDefinition } from "./types";

/** Canonical industry + job-role catalog for the app. */
export const CAREER_CATALOG: readonly IndustryDefinition[] = [
  {
    key: "technology",
    name: "Technology",
    order: 1,
    roles: [
      "Associate Software Engineer",
      "Junior Software Engineer",
      "Software Engineer",
      "SDE I",
      "SDE II",
      "Senior Software Engineer",
      "Lead Software Engineer",
      "Staff Engineer",
      "Principal Engineer",
      "Software Architect",
      "Solutions Architect",
      "Tech Lead",
      "Engineering Manager",
      "Senior Engineering Manager",
      "Director of Engineering",
      "VP Engineering",
      "CTO",
      "Full Stack Developer",
      "Full Stack Engineer",
      "MERN Stack Developer",
      "MEAN Stack Developer",
      "React Developer",
      "React.js Developer",
      "React Native Developer",
      "Node.js Developer",
      "Angular Developer",
      "Vue.js Developer",
      "Frontend Developer",
      "Frontend Engineer",
      "Frontend Lead",
      "UI Developer",
      "Backend Developer",
      "Backend Engineer",
      "Senior Backend Engineer",
      "Java Developer",
      "Python Developer",
      "Golang Developer",
      "Rust Developer",
      "PHP Developer",
      ".NET Developer",
      "C++ Developer",
      "Laravel Developer",
      "Django Developer",
      "Spring Boot Developer",
      "Flutter Developer",
      "Android Developer",
      "Senior Android Developer",
      "iOS Developer",
      "Senior iOS Engineer",
      "Mobile Developer",
      "Data Engineer",
      "Data Scientist",
      "Machine Learning Engineer",
      "AI Engineer",
      "Analytics Engineer",
      "Business Intelligence Developer",
      "DevOps Engineer",
      "Platform Engineer",
      "Site Reliability Engineer",
      "Cloud Engineer",
      "Cloud Architect",
      "AWS Engineer",
      "Security Engineer",
      "Cybersecurity Analyst",
      "QA Engineer",
      "QA Automation Engineer",
      "SDET",
      "Test Engineer",
      "Embedded Engineer",
      "Blockchain Developer",
      "Game Developer",
      "Network Engineer",
      "System Administrator",
      "Database Administrator",
      "Integration Engineer",
      "Product Manager",
      "Associate Product Manager",
      "Technical Product Manager",
      "Technical Program Manager",
      "Scrum Master",
      "Agile Coach",
      "UI/UX Designer",
      "Product Designer",
      "UX Researcher",
    ],
  },
  {
    key: "fintech",
    name: "Fintech",
    order: 2,
    roles: [
      "Software Engineer",
      "Senior Software Engineer",
      "Full Stack Developer",
      "Full Stack Engineer",
      "Backend Engineer",
      "Senior Backend Engineer",
      "Java Developer",
      "Python Developer",
      "React Developer",
      "Node.js Developer",
      "Data Engineer",
      "Data Scientist",
      "Machine Learning Engineer",
      "Quantitative Analyst",
      "Risk Analyst",
      "Compliance Analyst",
      "Financial Analyst",
      "Payment Product Manager",
      "Product Manager",
      "Technical Product Manager",
      "Tech Lead",
      "Engineering Manager",
      "Director of Engineering",
      "VP Engineering",
      "Solutions Architect",
      "DevOps Engineer",
      "Security Engineer",
      "Business Analyst",
    ],
  },
  {
    key: "sales_marketing",
    name: "Sales Marketing",
    order: 3,
    roles: [
      "Sales Executive",
      "Inside Sales Representative",
      "Outside Sales Representative",
      "Field Sales Executive",
      "Telesales Executive",
      "Business Development Representative",
      "Sales Development Representative",
      "Inside Sales Manager",
      "Sales Manager",
      "Regional Sales Manager",
      "Area Sales Manager",
      "Territory Sales Manager",
      "Enterprise Sales Manager",
      "Key Account Manager",
      "Strategic Account Manager",
      "Account Executive",
      "Senior Account Executive",
      "Pre-Sales Consultant",
      "Sales Consultant",
      "Channel Sales Manager",
      "Partner Manager",
      "Alliances Manager",
      "Head of Sales",
      "VP Sales",
      "Director of Sales",
      "Sales Operations Manager",
      "Revenue Operations Manager",
      "Lead Generation Specialist",
      "Marketing Executive",
      "Marketing Manager",
      "Digital Marketing Manager",
      "Digital Marketing Executive",
      "Performance Marketing Lead",
      "Performance Marketing Manager",
      "Growth Marketing Manager",
      "Growth Manager",
      "Demand Generation Manager",
      "Brand Manager",
      "Content Marketing Manager",
      "Content Writer",
      "Copywriter",
      "SEO Specialist",
      "SEO Executive",
      "SEM Specialist",
      "PPC Specialist",
      "Google Ads Specialist",
      "Meta Ads Specialist",
      "Social Media Manager",
      "Social Media Executive",
      "Email Marketing Specialist",
      "Marketing Analyst",
      "Marketing Coordinator",
      "Campaign Manager",
      "Product Marketing Manager",
      "Affiliate Marketing Manager",
      "Influencer Marketing Manager",
      "Event Marketing Manager",
      "Public Relations Manager",
      "Communications Manager",
      "CRM Manager",
      "Marketing Operations Manager",
      "Graphic Designer",
      "Creative Manager",
      "Customer Success Manager",
      "Customer Success Executive",
    ],
  },
  {
    key: "ecommerce",
    name: "E-commerce",
    order: 4,
    roles: [
      "Software Engineer",
      "SDE I",
      "SDE II",
      "Senior Software Engineer",
      "Full Stack Developer",
      "MERN Stack Developer",
      "React Developer",
      "Node.js Developer",
      "Python Developer",
      "Frontend Developer",
      "Frontend Engineer",
      "Frontend Lead",
      "Backend Engineer",
      "Product Engineer",
      "Data Analyst",
      "Product Manager",
      "Category Manager",
      "Merchandising Manager",
      "Catalog Manager",
      "Operations Manager",
      "Supply Chain Manager",
      "Warehouse Manager",
      "Logistics Manager",
      "Last Mile Operations Manager",
      "Digital Marketing Manager",
      "Performance Marketing Manager",
      "Growth Manager",
      "Customer Support Manager",
      "Engineering Manager",
      "Tech Lead",
    ],
  },
  {
    key: "saas",
    name: "SaaS",
    order: 5,
    roles: [
      "Software Engineer",
      "Senior Software Engineer",
      "Full Stack Developer",
      "Full Stack Engineer",
      "MERN Stack Developer",
      "React Developer",
      "Python Developer",
      "Node.js Developer",
      "Backend Engineer",
      "Product Engineer",
      "Solutions Engineer",
      "Solutions Architect",
      "Customer Success Manager",
      "Customer Success Executive",
      "Implementation Specialist",
      "Sales Development Representative",
      "Account Executive",
      "Enterprise Account Executive",
      "Product Manager",
      "Technical Product Manager",
      "Product Marketing Manager",
      "Growth Manager",
      "DevOps Engineer",
      "Tech Lead",
      "Engineering Manager",
      "Director of Engineering",
      "VP Engineering",
    ],
  },
  {
    key: "food_tech",
    name: "Food Tech",
    order: 6,
    roles: [
      "Software Engineer",
      "Senior Software Engineer",
      "Full Stack Developer",
      "React Developer",
      "Python Developer",
      "Android Developer",
      "iOS Developer",
      "Data Analyst",
      "Principal Engineer",
      "Operations Manager",
      "City Operations Manager",
      "Cluster Manager",
      "Supply Chain Manager",
      "Logistics Manager",
      "Product Manager",
      "Growth Manager",
      "Digital Marketing Manager",
      "Engineering Manager",
      "Tech Lead",
    ],
  },
  {
    key: "it_services",
    name: "IT Services",
    order: 7,
    roles: [
      "Software Engineer",
      "Senior Software Engineer",
      "Associate Software Engineer",
      "Java Developer",
      "Python Developer",
      "React Developer",
      "Angular Developer",
      ".NET Developer",
      "Full Stack Developer",
      "Backend Developer",
      "Frontend Developer",
      "Mobile Developer",
      "DevOps Engineer",
      "QA Engineer",
      "QA Automation Engineer",
      "Business Analyst",
      "Technical Business Analyst",
      "Consultant",
      "Senior Consultant",
      "Tech Lead",
      "Project Manager",
      "Delivery Manager",
      "Program Manager",
      "Engineering Manager",
      "HR Business Partner",
      "Talent Acquisition Lead",
      "Recruiter",
    ],
  },
  {
    key: "others",
    name: "Others",
    order: 8,
    roles: [
      "Software Engineer",
      "Full Stack Developer",
      "MERN Stack Developer",
      "React Developer",
      "Python Developer",
      "Rust Developer",
      "Java Developer",
      "Node.js Developer",
      "Data Analyst",
      "Business Analyst",
      "Product Manager",
      "Project Manager",
      "Program Manager",
      "Consultant",
      "Operations Manager",
      "Marketing Manager",
      "Sales Manager",
      "Account Executive",
      "HR Manager",
      "Recruiter",
      "Analyst",
      "Associate",
      "Manager",
      "Senior Manager",
      "Director",
      "VP",
      "Other",
    ],
  },
] as const;
