import type { IndustryKey } from "@/lib/career-catalog/types";
import type { SkillCategory, SkillGroupDefinition } from "./types";

/** Skills grouped by domain for maintainability. */
export const SKILL_GROUPS: readonly SkillGroupDefinition[] = [
  {
    category: "programmingLanguages",
    skills: [
      "JavaScript",
      "TypeScript",
      "Python",
      "Java",
      "C",
      "C++",
      "C#",
      "Go",
      "Golang",
      "Rust",
      "Ruby",
      "PHP",
      "Swift",
      "Kotlin",
      "Scala",
      "R",
      "SQL",
      "HTML",
      "CSS",
      "Shell Scripting",
      "Objective-C",
      "Dart",
    ],
  },
  {
    category: "webFrameworks",
    skills: [
      "React",
      "React.js",
      "Next.js",
      "Angular",
      "Vue.js",
      "Node.js",
      "Express.js",
      "NestJS",
      "Django",
      "Flask",
      "FastAPI",
      "Spring Boot",
      ".NET",
      "ASP.NET",
      "GraphQL",
      "REST APIs",
      "MERN Stack",
      "MEAN Stack",
      "Redux",
      "Webpack",
      "Vite",
      "Tailwind CSS",
      "Bootstrap",
      "Microservices",
      "System Design",
      "Data Structures",
      "Algorithms",
    ],
  },
  {
    category: "mobile",
    skills: [
      "Mobile Development",
      "Android",
      "iOS",
      "React Native",
      "Flutter",
      "SwiftUI",
      "Jetpack Compose",
      "Kotlin Multiplatform",
    ],
  },
  {
    category: "databases",
    skills: [
      "MongoDB",
      "PostgreSQL",
      "MySQL",
      "Redis",
      "Elasticsearch",
      "DynamoDB",
      "Firebase",
      "Oracle",
      "SQL Server",
      "Cassandra",
      "Neo4j",
    ],
  },
  {
    category: "cloudDevOps",
    skills: [
      "AWS",
      "Azure",
      "Google Cloud",
      "Docker",
      "Kubernetes",
      "Terraform",
      "Ansible",
      "CI/CD",
      "Jenkins",
      "GitHub Actions",
      "GitLab CI",
      "DevOps",
      "Linux",
      "Networking",
      "Cybersecurity",
      "Site Reliability Engineering",
      "Infrastructure as Code",
      "Cloud Architecture",
      "Nginx",
      "Apache Kafka",
      "RabbitMQ",
    ],
  },
  {
    category: "dataMl",
    skills: [
      "Data Analysis",
      "Data Engineering",
      "Data Science",
      "Machine Learning",
      "Deep Learning",
      "Natural Language Processing",
      "Computer Vision",
      "TensorFlow",
      "PyTorch",
      "Scikit-learn",
      "Pandas",
      "NumPy",
      "Apache Spark",
      "Hadoop",
      "ETL",
      "Power BI",
      "Tableau",
      "Looker",
      "BigQuery",
      "Snowflake",
      "dbt",
      "Statistics",
      "A/B Testing",
    ],
  },
  {
    category: "qaTesting",
    skills: [
      "QA",
      "Manual Testing",
      "Automation Testing",
      "QA Automation",
      "Selenium",
      "Cypress",
      "Playwright",
      "Jest",
      "Unit Testing",
      "Performance Testing",
      "API Testing",
      "Postman",
    ],
  },
  {
    category: "design",
    skills: [
      "UI/UX Design",
      "Figma",
      "Adobe XD",
      "Sketch",
      "Wireframing",
      "Prototyping",
      "Design Systems",
      "User Research",
      "Visual Design",
      "Graphic Design",
      "Adobe Photoshop",
      "Adobe Illustrator",
      "Canva",
    ],
  },
  {
    category: "productAgile",
    skills: [
      "Product Management",
      "Product Strategy",
      "Roadmapping",
      "Agile",
      "Scrum",
      "Kanban",
      "Jira",
      "Confluence",
      "Project Management",
      "Program Management",
      "Stakeholder Management",
      "Requirements Gathering",
      "User Stories",
      "OKRs",
    ],
  },
  {
    category: "salesMarketing",
    skills: [
      "Sales",
      "B2B Sales",
      "B2C Sales",
      "Inside Sales",
      "Field Sales",
      "Account Management",
      "Business Development",
      "Lead Generation",
      "Cold Calling",
      "Negotiation",
      "Marketing",
      "Digital Marketing",
      "Performance Marketing",
      "Growth Marketing",
      "Content Marketing",
      "Email Marketing",
      "Social Media Marketing",
      "SEO",
      "SEM",
      "PPC",
      "Google Ads",
      "Meta Ads",
      "Facebook Ads",
      "LinkedIn Ads",
      "Marketing Analytics",
      "Google Analytics",
      "HubSpot",
      "Marketo",
      "Salesforce",
      "CRM",
      "Copywriting",
      "Content Writing",
      "Brand Management",
      "Public Relations",
      "Customer Success",
      "Customer Support",
      "Community Management",
      "Influencer Marketing",
      "Affiliate Marketing",
      "Event Marketing",
    ],
  },
  {
    category: "finance",
    skills: [
      "Financial Modeling",
      "Financial Analysis",
      "Accounting",
      "Bookkeeping",
      "Budgeting",
      "Forecasting",
      "Risk Management",
      "Compliance",
      "KYC",
      "AML",
      "Payments",
      "FinTech",
      "Investment Banking",
      "Equity Research",
      "Taxation",
      "Auditing",
      "SAP FICO",
      "Tally",
      "QuickBooks",
    ],
  },
  {
    category: "ecommerceOps",
    skills: [
      "E-commerce",
      "Shopify",
      "WooCommerce",
      "Magento",
      "Supply Chain Management",
      "Inventory Management",
      "Logistics",
      "Warehouse Operations",
      "Order Management",
      "Vendor Management",
      "Procurement",
      "Operations Management",
      "Last Mile Delivery",
      "Catalog Management",
      "Merchandising",
    ],
  },
  {
    category: "hrRecruiting",
    skills: [
      "Recruitment",
      "Talent Acquisition",
      "HR Management",
      "Payroll",
      "Employee Relations",
      "Performance Management",
      "Learning and Development",
      "Compensation and Benefits",
      "HRIS",
      "Workday",
      "People Analytics",
    ],
  },
  {
    category: "softSkills",
    skills: [
      "Communication",
      "Leadership",
      "Problem Solving",
      "Critical Thinking",
      "Team Collaboration",
      "Time Management",
      "Presentation Skills",
      "Public Speaking",
      "Conflict Resolution",
      "Decision Making",
      "Adaptability",
      "Mentoring",
      "Cross-functional Collaboration",
    ],
  },
  {
    category: "toolsPlatforms",
    skills: [
      "Git",
      "GitHub",
      "GitLab",
      "Bitbucket",
      "VS Code",
      "IntelliJ IDEA",
      "Slack",
      "Microsoft Teams",
      "Notion",
      "Excel",
      "Google Sheets",
      "Microsoft Office",
      "PowerPoint",
      "Word",
      "SAP",
      "Oracle ERP",
      "ServiceNow",
      "Zapier",
      "Blockchain",
      "Web3",
      "Solidity",
      "IoT",
      "Embedded Systems",
    ],
  },
] as const;

/** Which skill categories apply to each industry. */
export const INDUSTRY_SKILL_CATEGORIES: Record<IndustryKey, readonly SkillCategory[]> = {
  technology: [
    "programmingLanguages",
    "webFrameworks",
    "mobile",
    "databases",
    "cloudDevOps",
    "dataMl",
    "qaTesting",
    "design",
    "productAgile",
    "softSkills",
    "toolsPlatforms",
  ],
  fintech: [
    "programmingLanguages",
    "webFrameworks",
    "databases",
    "cloudDevOps",
    "dataMl",
    "finance",
    "productAgile",
    "softSkills",
    "toolsPlatforms",
  ],
  sales_marketing: [
    "salesMarketing",
    "design",
    "dataMl",
    "productAgile",
    "softSkills",
    "toolsPlatforms",
  ],
  ecommerce: [
    "programmingLanguages",
    "webFrameworks",
    "databases",
    "cloudDevOps",
    "dataMl",
    "salesMarketing",
    "ecommerceOps",
    "productAgile",
    "softSkills",
    "toolsPlatforms",
  ],
  saas: [
    "programmingLanguages",
    "webFrameworks",
    "cloudDevOps",
    "dataMl",
    "salesMarketing",
    "productAgile",
    "softSkills",
    "toolsPlatforms",
  ],
  food_tech: [
    "programmingLanguages",
    "webFrameworks",
    "mobile",
    "dataMl",
    "ecommerceOps",
    "salesMarketing",
    "softSkills",
    "toolsPlatforms",
  ],
  it_services: [
    "programmingLanguages",
    "webFrameworks",
    "mobile",
    "databases",
    "cloudDevOps",
    "qaTesting",
    "productAgile",
    "softSkills",
    "toolsPlatforms",
  ],
  others: [
    "programmingLanguages",
    "webFrameworks",
    "mobile",
    "databases",
    "cloudDevOps",
    "dataMl",
    "salesMarketing",
    "finance",
    "design",
    "productAgile",
    "ecommerceOps",
    "hrRecruiting",
    "softSkills",
    "toolsPlatforms",
  ],
};

const skillsByCategory = new Map<SkillCategory, readonly string[]>(
  SKILL_GROUPS.map((group) => [group.category, group.skills]),
);

export function getSkillsForCategories(
  categories: readonly SkillCategory[],
): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const category of categories) {
    for (const skill of skillsByCategory.get(category) ?? []) {
      const key = skill.toLowerCase();
      if (seen.has(key)) continue;
      seen.add(key);
      out.push(skill);
    }
  }
  return out.sort((a, b) => a.localeCompare(b));
}

export const ALL_SKILLS = getSkillsForCategories(
  SKILL_GROUPS.map((group) => group.category),
);
